"""team_weekly_scores.updated_at — when scoring last wrote the row

Without it, a stale score and a correctly-recomputed identical score look
exactly the same, so "did scoring actually run?" can only be answered by
re-running the whole pipeline and diffing the totals.

NOTE ON AUTOGENERATE: the autogenerated version of this migration also wanted
to drop `competition_snapshots`, drop `ix_players_name_trgm` (the player-search
trigram index) and drop `ix_match_feed_cache_match_id`. None of that is
intended — those objects exist in the database and are created outside the
model metadata. Everything except the column was removed by hand. Read the
autogenerated file before upgrading; see migration_commands.sh.

Revision ID: 488add2426b5
Revises: a3c91d7e5b28
Create Date: 2026-08-16 15:02:26.504884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '488add2426b5'
down_revision: Union[str, Sequence[str], None] = 'a3c91d7e5b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add updated_at, backfilled to now() for existing rows.

    NOT NULL with a server_default is safe here: PostgreSQL 11+ records the
    default in the catalogue instead of rewriting the table, so this stays a
    fast metadata-only change even on a large table.
    """
    op.add_column(
        'team_weekly_scores',
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
    )


def downgrade() -> None:
    op.drop_column('team_weekly_scores', 'updated_at')
