"""add matches table and external api integration

Revision ID: 87b9b4cc2f07
Revises: f37971ec400e
Create Date: 2026-03-05 16:55:16.823772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b9b4cc2f07'
down_revision: Union[str, Sequence[str], None] = 'f37971ec400e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('external_api_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_players_external_api_id'), 'players', ['external_api_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_external_api_id'), table_name='players')
    op.drop_column('players', 'external_api_id')
    # ### end Alembic commands ###
