"""head to head matchups

Revision ID: da53bd8a49b2
Revises: 56d203ba3d99
Create Date: 2026-07-12 12:22:44.052457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da53bd8a49b2'
down_revision: Union[str, Sequence[str], None] = '56d203ba3d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_matchups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('transfer_window_id', sa.UUID(), nullable=False),
    sa.Column('home_team_id', sa.UUID(), nullable=False),
    sa.Column('away_team_id', sa.UUID(), nullable=True),
    sa.Column('home_points', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('away_points', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['fantasy_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['fantasy_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_window_id'], ['transfer_windows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_matchup_league_window', 'league_matchups', ['league_id', 'transfer_window_id'], unique=False)
    # server_default so this cleanly backfills existing rows on a populated table.
    op.add_column('leagues', sa.Column('is_head_to_head', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # Note: autogenerate also detected unrelated pre-existing drift (a dropped
    # match_feed_cache index, a dropped players trgm index, an added
    # real_teams index) — intentionally excluded from this migration; that
    # drift predates this feature and shouldn't be silently folded in here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'is_head_to_head')
    op.drop_index('ix_matchup_league_window', table_name='league_matchups')
    op.drop_table('league_matchups')
    # ### end Alembic commands ###
