"""budget_overage_points_penalty

Adds points_penalties: the ledger for budget-mode "cover a transfer's budget
overage with league points instead of being blocked" feature. One row per
transfer/staged-confirm event that charges points. Read-time only — nets
against TeamWeeklyScore.points in get_league_leaderboard() and ranking.py,
never mutates the raw scoring-engine-owned column.

Revision ID: dc8dfbef795d
Revises: 05b744b41b33
Create Date: 2026-07-08 11:37:37.353552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8dfbef795d'
down_revision: Union[str, Sequence[str], None] = '05b744b41b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_penalties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('fantasy_team_id', sa.UUID(), nullable=False),
    sa.Column('transfer_window_id', sa.UUID(), nullable=False),
    sa.Column('transfer_id', sa.UUID(), nullable=True),
    sa.Column('points_charged', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points_charged > 0', name='ck_points_penalty_positive'),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_window_id'], ['transfer_windows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_penalties_fantasy_team_id'), 'points_penalties', ['fantasy_team_id'], unique=False)
    op.create_index(op.f('ix_points_penalties_league_id'), 'points_penalties', ['league_id'], unique=False)
    op.create_index(op.f('ix_points_penalties_transfer_window_id'), 'points_penalties', ['transfer_window_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_penalties_transfer_window_id'), table_name='points_penalties')
    op.drop_index(op.f('ix_points_penalties_league_id'), table_name='points_penalties')
    op.drop_index(op.f('ix_points_penalties_fantasy_team_id'), table_name='points_penalties')
    op.drop_table('points_penalties')
    # ### end Alembic commands ###
