"""initial_schema_with_transfer_windows

Revision ID: f37971ec400e
Revises: 
Create Date: 2026-03-05 15:22:08.181068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37971ec400e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sports_name'), 'sports', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('auth_provider', sa.Enum('local', 'google', name='authprovider_enum'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(auth_provider = 'local'  AND password_hash IS NOT NULL) OR (auth_provider = 'google' AND google_id    IS NOT NULL)", name='ck_user_auth_provider_fields'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('default_scoring_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'action', name='uq_default_rule_sport_action')
    )
    op.create_index(op.f('ix_default_scoring_rules_sport_id'), 'default_scoring_rules', ['sport_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('real_team', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost >= 0', name='ck_player_cost_non_negative'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_sport_id'), 'players', ['sport_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_date < end_date', name='ck_season_dates'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'name', name='uq_season_sport_name'),
    sa.UniqueConstraint('sport_id', 'start_date', name='uq_season_sport_start')
    )
    op.create_index(op.f('ix_seasons_sport_id'), 'seasons', ['sport_id'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('SETUP', 'DRAFTING', 'ACTIVE', 'COMPLETED', name='leaguestatus_enum'), nullable=False),
    sa.Column('max_teams', sa.SmallInteger(), nullable=False),
    sa.Column('budget_per_team', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('squad_size', sa.SmallInteger(), nullable=False),
    sa.Column('draft_mode', sa.Boolean(), nullable=False),
    sa.Column('transfers_per_window', sa.SmallInteger(), nullable=False),
    sa.Column('transfer_day', sa.SmallInteger(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('budget_per_team > 0', name='ck_league_budget_positive'),
    sa.CheckConstraint('max_teams >= 2', name='ck_league_max_teams'),
    sa.CheckConstraint('squad_size >= 1', name='ck_league_squad_size'),
    sa.CheckConstraint('transfer_day >= 1 AND transfer_day <= 7', name='ck_league_transfer_day'),
    sa.CheckConstraint('transfers_per_window >= 0', name='ck_league_transfers_per_window'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'name', name='uq_league_season_name')
    )
    op.create_index(op.f('ix_leagues_invite_code'), 'leagues', ['invite_code'], unique=True)
    op.create_index(op.f('ix_leagues_owner_id'), 'leagues', ['owner_id'], unique=False)
    op.create_index(op.f('ix_leagues_season_id'), 'leagues', ['season_id'], unique=False)
    op.create_table('transfer_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transfer_deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lineup_deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transfers_locked', sa.Boolean(), nullable=False),
    sa.Column('lineup_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lineup_deadline_at <= end_at', name='ck_transfer_window_lineup_before_end'),
    sa.CheckConstraint('number > 0', name='ck_transfer_window_number_positive'),
    sa.CheckConstraint('start_at < end_at', name='ck_transfer_window_times'),
    sa.CheckConstraint('transfer_deadline_at < lineup_deadline_at', name='ck_transfer_window_transfer_before_lineup'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'number', name='uq_transfer_window_season_number')
    )
    op.create_index(op.f('ix_transfer_windows_season_id'), 'transfer_windows', ['season_id'], unique=False)
    op.create_table('fantasy_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_budget >= 0', name='ck_team_budget_non_negative'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'user_id', name='uq_team_league_user')
    )
    op.create_index(op.f('ix_fantasy_teams_league_id'), 'fantasy_teams', ['league_id'], unique=False)
    op.create_index(op.f('ix_fantasy_teams_user_id'), 'fantasy_teams', ['user_id'], unique=False)
    op.create_table('league_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('draft_position', sa.SmallInteger(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('draft_position > 0', name='ck_membership_draft_pos'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'draft_position', name='uq_membership_league_draft_pos'),
    sa.UniqueConstraint('league_id', 'user_id', name='uq_membership_league_user')
    )
    op.create_index(op.f('ix_league_memberships_league_id'), 'league_memberships', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_memberships_user_id'), 'league_memberships', ['user_id'], unique=False)
    op.create_table('league_scoring_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'sport_id', 'action', name='uq_override_league_sport_action')
    )
    op.create_index(op.f('ix_league_scoring_overrides_league_id'), 'league_scoring_overrides', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_scoring_overrides_sport_id'), 'league_scoring_overrides', ['sport_id'], unique=False)
    op.create_table('league_sports',
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('league_id', 'sport_id')
    )
    op.create_table('lineup_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('min_count', sa.SmallInteger(), nullable=False),
    sa.Column('max_count', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('min_count <= max_count', name='ck_lineup_min_le_max'),
    sa.CheckConstraint('min_count >= 0', name='ck_lineup_min_count'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'sport_id', 'position', name='uq_lineup_league_sport_position')
    )
    op.create_index(op.f('ix_lineup_slots_league_id'), 'lineup_slots', ['league_id'], unique=False)
    op.create_index(op.f('ix_lineup_slots_sport_id'), 'lineup_slots', ['sport_id'], unique=False)
    op.create_table('player_gameweek_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('transfer_window_id', sa.UUID(), nullable=False),
    sa.Column('minutes_played', sa.SmallInteger(), nullable=False),
    sa.Column('fantasy_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('minutes_played <= 120', name='ck_stat_minutes_max'),
    sa.CheckConstraint('minutes_played >= 0', name='ck_stat_minutes_non_negative'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_window_id'], ['transfer_windows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'transfer_window_id', name='uq_player_gameweek_stat')
    )
    op.create_index(op.f('ix_player_gameweek_stats_player_id'), 'player_gameweek_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_gameweek_stats_transfer_window_id'), 'player_gameweek_stats', ['transfer_window_id'], unique=False)
    op.create_table('cricket_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_stat_id', sa.UUID(), nullable=False),
    sa.Column('runs_scored', sa.SmallInteger(), nullable=True),
    sa.Column('balls_faced', sa.SmallInteger(), nullable=True),
    sa.Column('wickets_taken', sa.SmallInteger(), nullable=True),
    sa.Column('maidens', sa.SmallInteger(), nullable=True),
    sa.Column('economy_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('catches', sa.SmallInteger(), nullable=True),
    sa.Column('run_outs', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('balls_faced IS NULL OR balls_faced >= 0', name='ck_cr_balls_faced'),
    sa.CheckConstraint('catches IS NULL OR catches >= 0', name='ck_cr_catches'),
    sa.CheckConstraint('economy_rate IS NULL OR economy_rate >= 0', name='ck_cr_economy_rate'),
    sa.CheckConstraint('maidens IS NULL OR maidens >= 0', name='ck_cr_maidens'),
    sa.CheckConstraint('run_outs IS NULL OR run_outs >= 0', name='ck_cr_run_outs'),
    sa.CheckConstraint('runs_scored IS NULL OR runs_scored >= 0', name='ck_cr_runs_scored'),
    sa.CheckConstraint('wickets_taken IS NULL OR wickets_taken >= 0', name='ck_cr_wickets_taken'),
    sa.ForeignKeyConstraint(['base_stat_id'], ['player_gameweek_stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_stat_id')
    )
    op.create_table('draft_picks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('fantasy_team_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.SmallInteger(), nullable=False),
    sa.Column('pick_number', sa.SmallInteger(), nullable=False),
    sa.Column('picked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pick_number >= 1', name='ck_draft_pick_positive'),
    sa.CheckConstraint('round_number >= 1', name='ck_draft_round_positive'),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'pick_number', name='uq_draft_pick_league_pick_number'),
    sa.UniqueConstraint('league_id', 'player_id', name='uq_draft_pick_league_player')
    )
    op.create_index(op.f('ix_draft_picks_fantasy_team_id'), 'draft_picks', ['fantasy_team_id'], unique=False)
    op.create_index(op.f('ix_draft_picks_league_id'), 'draft_picks', ['league_id'], unique=False)
    op.create_table('football_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_stat_id', sa.UUID(), nullable=False),
    sa.Column('goals', sa.SmallInteger(), nullable=False),
    sa.Column('assists', sa.SmallInteger(), nullable=False),
    sa.Column('clean_sheets', sa.SmallInteger(), nullable=False),
    sa.Column('yellow_cards', sa.SmallInteger(), nullable=False),
    sa.Column('red_cards', sa.SmallInteger(), nullable=False),
    sa.Column('own_goals', sa.SmallInteger(), nullable=False),
    sa.Column('penalties_saved', sa.SmallInteger(), nullable=False),
    sa.Column('penalties_missed', sa.SmallInteger(), nullable=False),
    sa.Column('saves', sa.SmallInteger(), nullable=False),
    sa.Column('goals_conceded', sa.SmallInteger(), nullable=False),
    sa.Column('bonus', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('assists >= 0', name='ck_fb_assists'),
    sa.CheckConstraint('bonus >= 0', name='ck_fb_bonus'),
    sa.CheckConstraint('clean_sheets >= 0', name='ck_fb_clean_sheets'),
    sa.CheckConstraint('goals >= 0', name='ck_fb_goals'),
    sa.CheckConstraint('goals_conceded >= 0', name='ck_fb_goals_conceded'),
    sa.CheckConstraint('own_goals >= 0', name='ck_fb_own_goals'),
    sa.CheckConstraint('penalties_missed >= 0', name='ck_fb_penalties_missed'),
    sa.CheckConstraint('penalties_saved >= 0', name='ck_fb_penalties_saved'),
    sa.CheckConstraint('red_cards <= 1', name='ck_fb_red_cards_max'),
    sa.CheckConstraint('red_cards >= 0', name='ck_fb_red_cards'),
    sa.CheckConstraint('saves >= 0', name='ck_fb_saves'),
    sa.CheckConstraint('yellow_cards <= 2', name='ck_fb_yellow_cards_max'),
    sa.CheckConstraint('yellow_cards >= 0', name='ck_fb_yellow_cards'),
    sa.ForeignKeyConstraint(['base_stat_id'], ['player_gameweek_stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_stat_id')
    )
    op.create_table('team_gameweek_lineups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fantasy_team_id', sa.UUID(), nullable=False),
    sa.Column('transfer_window_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('is_vice_captain', sa.Boolean(), nullable=False),
    sa.CheckConstraint('NOT (is_captain AND is_vice_captain)', name='ck_lineup_not_captain_and_vice'),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['transfer_window_id'], ['transfer_windows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fantasy_team_id', 'transfer_window_id', 'player_id', name='uq_lineup_team_window_player')
    )
    op.create_index(op.f('ix_team_gameweek_lineups_fantasy_team_id'), 'team_gameweek_lineups', ['fantasy_team_id'], unique=False)
    op.create_index(op.f('ix_team_gameweek_lineups_transfer_window_id'), 'team_gameweek_lineups', ['transfer_window_id'], unique=False)
    op.create_index('uq_one_captain_per_team_window', 'team_gameweek_lineups', ['fantasy_team_id', 'transfer_window_id'], unique=True, postgresql_where=sa.text('is_captain = TRUE'))
    op.create_index('uq_one_vice_captain_per_team_window', 'team_gameweek_lineups', ['fantasy_team_id', 'transfer_window_id'], unique=True, postgresql_where=sa.text('is_vice_captain = TRUE'))
    op.create_table('team_players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fantasy_team_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('acquired_window_id', sa.UUID(), nullable=False),
    sa.Column('released_window_id', sa.UUID(), nullable=True),
    sa.Column('cost_at_acquisition', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost_at_acquisition >= 0', name='ck_team_player_cost_non_negative'),
    sa.ForeignKeyConstraint(['acquired_window_id'], ['transfer_windows.id'], ),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['released_window_id'], ['transfer_windows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fantasy_team_id', 'player_id', 'acquired_window_id', name='uq_team_player_acquired')
    )
    op.create_index(op.f('ix_team_players_fantasy_team_id'), 'team_players', ['fantasy_team_id'], unique=False)
    op.create_index(op.f('ix_team_players_player_id'), 'team_players', ['player_id'], unique=False)
    op.create_index('uix_team_player_active', 'team_players', ['fantasy_team_id', 'player_id'], unique=True, postgresql_where=sa.text('released_window_id IS NULL'))
    op.create_table('team_weekly_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fantasy_team_id', sa.UUID(), nullable=False),
    sa.Column('transfer_window_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('rank_in_league', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('rank_in_league IS NULL OR rank_in_league >= 1', name='ck_weekly_score_rank_positive'),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_window_id'], ['transfer_windows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fantasy_team_id', 'transfer_window_id', name='uq_weekly_score_team_window')
    )
    op.create_index(op.f('ix_team_weekly_scores_fantasy_team_id'), 'team_weekly_scores', ['fantasy_team_id'], unique=False)
    op.create_index(op.f('ix_team_weekly_scores_transfer_window_id'), 'team_weekly_scores', ['transfer_window_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fantasy_team_id', sa.UUID(), nullable=False),
    sa.Column('transfer_window_id', sa.UUID(), nullable=False),
    sa.Column('player_out_id', sa.UUID(), nullable=False),
    sa.Column('player_in_id', sa.UUID(), nullable=False),
    sa.Column('cost_at_transfer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost_at_transfer >= 0', name='ck_transfer_cost_non_negative'),
    sa.CheckConstraint('player_out_id != player_in_id', name='ck_transfer_different_players'),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_in_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_out_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['transfer_window_id'], ['transfer_windows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transfer_team_window', 'transfers', ['fantasy_team_id', 'transfer_window_id'], unique=False)
    op.create_index(op.f('ix_transfers_fantasy_team_id'), 'transfers', ['fantasy_team_id'], unique=False)
    op.create_index(op.f('ix_transfers_transfer_window_id'), 'transfers', ['transfer_window_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_transfer_window_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_fantasy_team_id'), table_name='transfers')
    op.drop_index('ix_transfer_team_window', table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_team_weekly_scores_transfer_window_id'), table_name='team_weekly_scores')
    op.drop_index(op.f('ix_team_weekly_scores_fantasy_team_id'), table_name='team_weekly_scores')
    op.drop_table('team_weekly_scores')
    op.drop_index('uix_team_player_active', table_name='team_players', postgresql_where=sa.text('released_window_id IS NULL'))
    op.drop_index(op.f('ix_team_players_player_id'), table_name='team_players')
    op.drop_index(op.f('ix_team_players_fantasy_team_id'), table_name='team_players')
    op.drop_table('team_players')
    op.drop_index('uq_one_vice_captain_per_team_window', table_name='team_gameweek_lineups', postgresql_where=sa.text('is_vice_captain = TRUE'))
    op.drop_index('uq_one_captain_per_team_window', table_name='team_gameweek_lineups', postgresql_where=sa.text('is_captain = TRUE'))
    op.drop_index(op.f('ix_team_gameweek_lineups_transfer_window_id'), table_name='team_gameweek_lineups')
    op.drop_index(op.f('ix_team_gameweek_lineups_fantasy_team_id'), table_name='team_gameweek_lineups')
    op.drop_table('team_gameweek_lineups')
    op.drop_table('football_stats')
    op.drop_index(op.f('ix_draft_picks_league_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_fantasy_team_id'), table_name='draft_picks')
    op.drop_table('draft_picks')
    op.drop_table('cricket_stats')
    op.drop_index(op.f('ix_player_gameweek_stats_transfer_window_id'), table_name='player_gameweek_stats')
    op.drop_index(op.f('ix_player_gameweek_stats_player_id'), table_name='player_gameweek_stats')
    op.drop_table('player_gameweek_stats')
    op.drop_index(op.f('ix_lineup_slots_sport_id'), table_name='lineup_slots')
    op.drop_index(op.f('ix_lineup_slots_league_id'), table_name='lineup_slots')
    op.drop_table('lineup_slots')
    op.drop_table('league_sports')
    op.drop_index(op.f('ix_league_scoring_overrides_sport_id'), table_name='league_scoring_overrides')
    op.drop_index(op.f('ix_league_scoring_overrides_league_id'), table_name='league_scoring_overrides')
    op.drop_table('league_scoring_overrides')
    op.drop_index(op.f('ix_league_memberships_user_id'), table_name='league_memberships')
    op.drop_index(op.f('ix_league_memberships_league_id'), table_name='league_memberships')
    op.drop_table('league_memberships')
    op.drop_index(op.f('ix_fantasy_teams_user_id'), table_name='fantasy_teams')
    op.drop_index(op.f('ix_fantasy_teams_league_id'), table_name='fantasy_teams')
    op.drop_table('fantasy_teams')
    op.drop_index(op.f('ix_transfer_windows_season_id'), table_name='transfer_windows')
    op.drop_table('transfer_windows')
    op.drop_index(op.f('ix_leagues_season_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_owner_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_invite_code'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_seasons_sport_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_players_sport_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_default_scoring_rules_sport_id'), table_name='default_scoring_rules')
    op.drop_table('default_scoring_rules')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sports_name'), table_name='sports')
    op.drop_table('sports')
    # ### end Alembic commands ###
