"""add league chat messages and reactions

Revision ID: fc7c3576ed77
Revises: 579db2a81210
Create Date: 2026-07-08 04:10:52.036705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7c3576ed77'
down_revision: Union[str, Sequence[str], None] = '579db2a81210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# NOTE: autogenerate also proposed touching indexes on match_feed_cache/
# players/real_teams — pre-existing, unrelated index-level drift (same as
# the last two migrations). Trimmed by hand to only the two new chat tables.


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_chat_messages_league_id'), 'league_chat_messages', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_chat_messages_user_id'), 'league_chat_messages', ['user_id'], unique=False)
    op.create_table('league_chat_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['league_chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_chat_reaction_message_user_emoji')
    )
    op.create_index(op.f('ix_league_chat_reactions_message_id'), 'league_chat_reactions', ['message_id'], unique=False)
    op.create_index(op.f('ix_league_chat_reactions_user_id'), 'league_chat_reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_league_chat_reactions_user_id'), table_name='league_chat_reactions')
    op.drop_index(op.f('ix_league_chat_reactions_message_id'), table_name='league_chat_reactions')
    op.drop_table('league_chat_reactions')
    op.drop_index(op.f('ix_league_chat_messages_user_id'), table_name='league_chat_messages')
    op.drop_index(op.f('ix_league_chat_messages_league_id'), table_name='league_chat_messages')
    op.drop_table('league_chat_messages')
    # ### end Alembic commands ###
